# Generated by Django 6.0.1 on 2026-06-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="userskill",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekdays", "Weekdays"),
                    ("weekends", "Weekends"),
                    ("flexible", "Flexible"),
                ],
                default="flexible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userskill",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userskill",
            name="experience_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("expert", "Expert"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
    ]
