# Generated by Django 6.0.1 on 2026-02-10 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_initial"),
        ("swaps", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swaprequest",
            name="skill_offered",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offered_in_swaps",
                to="skills.skill",
            ),
        ),
        migrations.AlterField(
            model_name="swaprequest",
            name="skill_requested",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_in_swaps",
                to="skills.skill",
            ),
        ),
    ]
