# Generated by Django 6.0.1 on 2026-02-10 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_initial"),
        ("swaps", "0003_alter_swaprequest_skill_offered_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="swaprequest",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_swaps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="swaprequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_swaps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="swaprequest",
            name="skill_offered",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offered_swaps",
                to="skills.skill",
            ),
        ),
        migrations.AlterField(
            model_name="swaprequest",
            name="skill_requested",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_swaps",
                to="skills.skill",
            ),
        ),
        migrations.AlterField(
            model_name="swaprequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="swaprequest",
            unique_together={
                ("requester", "receiver", "skill_offered", "skill_requested")
            },
        ),
    ]
