# Generated by Django 6.0.1 on 2026-06-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekdays", "Weekdays"),
                    ("weekends", "Weekends"),
                    ("flexible", "Flexible"),
                ],
                default="flexible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.FileField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
